apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
      - name: init-container
        image: nginx:latest
        args:
        - "nginx"
        - "-g"
        - "daemon off;"
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: nginx-volume
          mountPath: /
        - name: config-volume
          mountPath: /etc/nginx
      volume:
      - name: nginx-volume
        emptyDir: {}
      - name: config-volume
        emptyDir: {}
